---
bases:
  - helmfile-common.yaml

releases:
  - name: kafka
    chart: bitnami/kafka
    version: 9.0.4
    namespace: {{ requiredEnv "TARGET_NAMESPACE" }}
    values:
      - values/kafka.yaml.gotmpl
