---
bases:
  - helmfile-common.yaml

releases:
  - name: redis-nonce
    namespace: {{ requiredEnv "TARGET_NAMESPACE" }}
    chart: bitnami/redis
    version: 10.6.0
    atomic: true
    values:
      - values/redis.yaml
      - values/redis-nonce.yaml
  - name: postgresql-envelope-store
    namespace: {{ requiredEnv "TARGET_NAMESPACE" }}
    chart: bitnami/postgresql
    atomic: true
    version: 8.6.12
    values:
      - values/postgresql-envelope-store.yaml.gotmpl
  - name: postgresql-contract-registry
    namespace: {{ requiredEnv "TARGET_NAMESPACE" }}
    chart: bitnami/postgresql
    atomic: true
    version: 8.6.12
    values:
      - values/postgresql-contract-registry.yaml.gotmpl
  - name: postgresql-chain-registry
    namespace: {{ requiredEnv "TARGET_NAMESPACE" }}
    chart: bitnami/postgresql
    atomic: true
    version: 8.6.12
    values:
      - values/postgresql-chain-registry.yaml.gotmpl
