---
helmDefaults:
  verify: false
  wait: true
  timeout: 600
  recreatePods: false
  force: false
environments:
  orchestrate-demo:
    values:
      - environments/orchestrate-demo.yaml
      - values/tags.yaml
repositories:
  - name: helm-pegasys
    url: https://pegasys.jfrog.io/artifactory/helm-pegasys/
  - name: bitnami
    url: https://charts.bitnami.com/bitnami/