# See https://github.com/helm/charts/tree/master/incubator/kafka#connecting-to-kafka-from-inside-kubernetes
apiVersion: v1
kind: Pod
metadata:
  name: testclient
  namespace: kafka
spec:
  containers:
  - name: kafka
    image: solsson/kafka:0.11.0.0
    command:
      - sh
      - -c
      - "exec tail -f /dev/null"
